
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Add_BykeForm extends javax.swing.JFrame {
    public ArrayList<Product>products(){
    ArrayList<Product>products = new ArrayList<>();
    try{
        Class.forName("com.mysql.jdbc.Driver");
        
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/addbyke","root","");
        String query ="select * from added";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
         Product product;
         while(rs.next()){
         product=new Product( rs.getInt("id"),rs.getString("byke_name"), rs.getFloat("retailer_price"), rs.getFloat("customer_price"), rs.getInt("quantity"));
         products.add(product);
         }
  
    }
    catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
}
    return products;
}
    public void show_user(){
    ArrayList<Product>list=products();
    DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
    Object[] row = new Object[5];
    for(int i=0;i<list.size();i++){
    row[0]=list.get(i).getId();
    row[1]=list.get(i).getByke_Name();
    row[2]=list.get(i).getRetailer_Price();
    row[3]=list.get(i).getCustomer_Price();
    row[4]=list.get(i).getQuantity();
    model.addRow(row);
    
    }
    
    }

    /**
     * Creates new form Add_BykeForm
     */
    public Add_BykeForm() {
        initComponents();
        show_user();
        //initData();
    }
    
//    public void initData(){
//    //products.add(new Product("R15", 20000, 450000, 10));
//    products = repo.loadProducts();
//        setItem();
//    }
//    public void setItem(){
//    String[]items = new String[products.size()];
//    for(int i = 0;i<products.size();i++){
//    Product p = products.get(i);
//    items[i]=p.getByke_Name();
//    }
//   
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_BykeName = new javax.swing.JLabel();
        jTextField_BykeName = new javax.swing.JTextField();
        jLabel_RetailerPrice = new javax.swing.JLabel();
        jTextField_RetailerPrice = new javax.swing.JTextField();
        jLabel_CustomerPrice = new javax.swing.JLabel();
        jTextField_CustomerPrice = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        jTextField_quantity = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButton_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel_BykeName.setText("Byke Name");
        jPanel1.add(jLabel_BykeName);
        jLabel_BykeName.setBounds(850, 270, 80, 14);
        jPanel1.add(jTextField_BykeName);
        jTextField_BykeName.setBounds(950, 260, 170, 30);

        jLabel_RetailerPrice.setText("Retailer Price");
        jPanel1.add(jLabel_RetailerPrice);
        jLabel_RetailerPrice.setBounds(850, 330, 90, 14);
        jPanel1.add(jTextField_RetailerPrice);
        jTextField_RetailerPrice.setBounds(950, 320, 170, 30);

        jLabel_CustomerPrice.setText("Customer Price");
        jPanel1.add(jLabel_CustomerPrice);
        jLabel_CustomerPrice.setBounds(840, 390, 90, 14);
        jPanel1.add(jTextField_CustomerPrice);
        jTextField_CustomerPrice.setBounds(950, 380, 170, 30);

        jLabelQuantity.setText("Quantity");
        jPanel1.add(jLabelQuantity);
        jLabelQuantity.setBounds(850, 450, 80, 14);
        jPanel1.add(jTextField_quantity);
        jTextField_quantity.setBounds(950, 440, 170, 30);

        jButtonSave.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSave.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave);
        jButtonSave.setBounds(920, 540, 73, 23);

        jButton_Home.setBackground(new java.awt.Color(153, 153, 153));
        jButton_Home.setForeground(new java.awt.Color(51, 0, 0));
        jButton_Home.setText("Home");
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Home);
        jButton_Home.setBounds(1040, 540, 70, 23);

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jTable1_Display_User.setBackground(new java.awt.Color(102, 102, 102));
        jTable1_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID","Byke Name", "Retailer Price", "Customer Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1_Display_User);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 330, 452, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc9lab2\\Desktop\\BykeProject\\Looks.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 1610, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Admin_Page ad = new Admin_Page();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/addbyke","root","");
        String query= "insert into added(Byke_Name,Retailer_Price,Customer_Price,Quantity) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, jTextField_BykeName.getText());
           pst.setFloat(2,Integer.parseInt(jTextField_RetailerPrice.getText()));
           
           pst.setFloat(3, Integer.parseInt(jTextField_CustomerPrice.getText()));
           pst.setString(4,jTextField_quantity.getText()); 
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insert Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Add_BykeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Add_BykeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Add_BykeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Add_BykeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Add_BykeForm().setVisible(true);  
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabel_BykeName;
    private javax.swing.JLabel jLabel_CustomerPrice;
    private javax.swing.JLabel jLabel_RetailerPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_User;
    private javax.swing.JTextField jTextField_BykeName;
    private javax.swing.JTextField jTextField_CustomerPrice;
    private javax.swing.JTextField jTextField_RetailerPrice;
    private javax.swing.JTextField jTextField_quantity;
    // End of variables declaration//GEN-END:variables
}
