
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Delete_Byke extends javax.swing.JFrame {
    
      public ArrayList<Product>products(){
    ArrayList<Product>products = new ArrayList<>();
    try{
        Class.forName("com.mysql.jdbc.Driver");
        
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/addbyke","root","");
        String query ="select * from added";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
         Product product;
         while(rs.next()){
         product=new Product( rs.getInt("id"),rs.getString("byke_name"), rs.getFloat("retailer_price"), rs.getFloat("customer_price"), rs.getInt("quantity"));
         products.add(product);
         }
  
    }
    catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
}
        return products;
}
    

       public void show_user(){
    ArrayList<Product>list=products();
    DefaultTableModel model = (DefaultTableModel)jTable1_Display.getModel();
    Object[] row = new Object[5];
    for(int i=0;i<list.size();i++){
    row[0] = list.get(i).getId();
    row[1]=list.get(i).getByke_Name();
    row[2]=list.get(i).getRetailer_Price();
    row[3]=list.get(i).getCustomer_Price();
    row[4]=list.get(i).getQuantity();
    model.addRow(row);
    
    }
    
    }

    /**
     * Creates new form Delete_Byke
     */
    public Delete_Byke() {
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_BykeNameID = new javax.swing.JTextField();
        jLabel_BykeName = new javax.swing.JLabel();
        jLabel_quantity = new javax.swing.JLabel();
        jTextField_Quantity = new javax.swing.JTextField();
        jButton_Save = new javax.swing.JButton();
        jButton_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jTextField_BykeNameID.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_BykeNameID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField_BykeNameID);
        jTextField_BykeNameID.setBounds(570, 90, 140, 30);

        jLabel_BykeName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BykeName.setText("Byke Id");
        jPanel1.add(jLabel_BykeName);
        jLabel_BykeName.setBounds(480, 100, 70, 14);

        jLabel_quantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_quantity.setText("Quantity");
        jPanel1.add(jLabel_quantity);
        jLabel_quantity.setBounds(480, 170, 80, 14);
        jPanel1.add(jTextField_Quantity);
        jTextField_Quantity.setBounds(570, 160, 140, 30);

        jButton_Save.setBackground(new java.awt.Color(0, 51, 255));
        jButton_Save.setForeground(new java.awt.Color(102, 102, 102));
        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Save);
        jButton_Save.setBounds(490, 220, 57, 23);

        jButton_Home.setText("Home");
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Home);
        jButton_Home.setBounds(580, 220, 100, 23);

        jTable1_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id","Byke Name", "Retailer Price", "Customer Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1_Display);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 410, 100);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1170, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Admin_Page ad = new Admin_Page();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/addbyke","root","");
        String query= "DELETE FROM `added` WHERE id=? ";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, jTextField_BykeNameID.getText());
            
          
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
            
            
        
    }//GEN-LAST:event_jButton_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Delete_Byke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Delete_Byke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Delete_Byke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Delete_Byke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Delete_Byke().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_BykeName;
    private javax.swing.JLabel jLabel_quantity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display;
    private javax.swing.JTextField jTextField_BykeNameID;
    private javax.swing.JTextField jTextField_Quantity;
    // End of variables declaration//GEN-END:variables
}
