/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FirstName = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel_EmailId = new javax.swing.JLabel();
        jTextFieldEmailId = new javax.swing.JTextField();
        jLabel_UserName = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel_Password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField2_ReType = new javax.swing.JPasswordField();
        jLabel_Mobil = new javax.swing.JLabel();
        jTextField_MobileNumber = new javax.swing.JTextField();
        jButton_Register = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_FirstName.setText("First_Name");
        jPanel1.add(jLabel_FirstName);
        jLabel_FirstName.setBounds(330, 240, 70, 15);
        jPanel1.add(jTextField_FirstName);
        jTextField_FirstName.setBounds(420, 240, 140, 20);

        LastName.setText("Last_Name");
        jPanel1.add(LastName);
        LastName.setBounds(610, 240, 60, 14);
        jPanel1.add(jTextField_LastName);
        jTextField_LastName.setBounds(710, 240, 140, 20);

        jLabel_EmailId.setText("Email_Id");
        jPanel1.add(jLabel_EmailId);
        jLabel_EmailId.setBounds(330, 300, 50, 14);
        jPanel1.add(jTextFieldEmailId);
        jTextFieldEmailId.setBounds(420, 290, 140, 20);

        jLabel_UserName.setText("User_Name");
        jPanel1.add(jLabel_UserName);
        jLabel_UserName.setBounds(610, 290, 70, 14);
        jPanel1.add(jTextField_UserName);
        jTextField_UserName.setBounds(710, 290, 140, 20);

        jLabel_Password.setText("Password");
        jPanel1.add(jLabel_Password);
        jLabel_Password.setBounds(330, 360, 60, 14);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(420, 350, 140, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Re-type Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 340, 90, 14);
        jPanel1.add(jPasswordField2_ReType);
        jPasswordField2_ReType.setBounds(710, 340, 140, 20);

        jLabel_Mobil.setText("Mobile Number");
        jPanel1.add(jLabel_Mobil);
        jLabel_Mobil.setBounds(330, 420, 70, 14);
        jPanel1.add(jTextField_MobileNumber);
        jTextField_MobileNumber.setBounds(420, 410, 140, 20);

        jButton_Register.setText("Register");
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Register);
        jButton_Register.setBounds(510, 520, 80, 23);

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(690, 520, 55, 23);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 1240, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login_Page lo = new Login_Page();
        lo.setVisible(true);
        
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_EmailId;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_Mobil;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2_ReType;
    private javax.swing.JTextField jTextFieldEmailId;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_MobileNumber;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
